# Generated by Django 4.1.3 on 2023-05-31 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drums',
            fields=[
                ('Sno', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=500)),
                ('Phoneno', models.IntegerField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Guitar',
            fields=[
                ('Sno', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=500)),
                ('Phoneno', models.IntegerField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Piano',
            fields=[
                ('Sno', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=500)),
                ('Phoneno', models.IntegerField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Violin',
            fields=[
                ('Sno', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=500)),
                ('Phoneno', models.IntegerField(max_length=100)),
            ],
        ),
    ]
