# Generated by Django 4.1.3 on 2023-06-05 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appy', '0003_userinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drums',
            name='Name',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='drums',
            name='Phoneno',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='guitar',
            name='Name',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='guitar',
            name='Phoneno',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='piano',
            name='Name',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='piano',
            name='Phoneno',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='Email',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='Name',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='Passwd',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='Phoneno',
            field=models.CharField(max_length=5000, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='violin',
            name='Name',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='violin',
            name='Phoneno',
            field=models.CharField(max_length=5000),
        ),
    ]
